### ISSUE TITLE
Guide for build 

### ISSUE THREAD

**Issue by enzodello** [mausi-mick/KS_ESP32#1]
do I have to connect all the diagrams in the folder together?
which sketch should i load on esp32?
 could you describe what each .ino file is for?

**Comment by mausi-mick** [comment]
At first You need the new Arduino IDE 2.3.2 ( I used version 1.8.13, but it was very slow) for the sketches ( .ino) and Header (.h) and the KiCad version 8.0 or higher for the schematics, pcbs, .

there are 3 "big" boards, 

  ESP32_R ...      for the ESP32 (38 pin)
  UCE_Board_2  with dual-DAC MCP4822  (for Uce / Uds) and the ADC MCP3204 and Power Amplifier TCA0372
  CCS_I2C         for the isolated precision Currentsource

and 2 small boards piggyback on the CCS_I2C board:

 CCS_Switch_BE_1            small Board with 4Photomos-Relais
 IC2_Adum_MCP4725_1  small Board with Adum-Isolator and DAC_MCP4725

Then scetches : 
  Curve_Tracer_ESP32_ILI9341_BMP_6_Touch_Menu_2
  Generic_Touch_Calibration

A diagram for connection CurveTracer (CT) to modified Transistortester (TT)
 Connection TT_SerialWrite with CT

and some h. files
